name: CD
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    outputs:
      profile: ${{ steps.set-profile.outputs.profile }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GIT_ACTION_TOKEN }}
          submodules: true

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission for Gradlew
        run: chmod +x gradlew

      - name: Set Spring profile by branch
        id: set-profile
        run: |
          echo "PROFILE=prod" >> $GITHUB_ENV
          echo "profile=prod" >> $GITHUB_OUTPUT

      - name: Build with Gradle
        run: ./gradlew clean bootjar -Pprofile=${PROFILE}

      - name: Docker build & push
        run: docker buildx build -f ./docker/Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }} --push .

  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy on server
        uses: appleboy/ssh-action@master
        env:
          PROFILE: ${{ needs.build.outputs.profile }}
          ENV_PROD: ${{ secrets.ENV_PROD }}
        with:
          envs: PROFILE, ENV_PROD
          host: ${{ github.ref == 'refs/heads/main' && secrets.SSH_HOST_PROD }}
          port: ${{ github.ref == 'refs/heads/main' && secrets.SSH_PORT_PROD }}
          username: ${{ github.ref == 'refs/heads/main' && secrets.SSH_USERNAME_PROD }}
          key: ${{ github.ref == 'refs/heads/main' && secrets.SSH_PRIVATE_KEY_PROD }}
          script: |
            cd /home/ubuntu/actions-runner/_work/BE/BE/docker
            echo "$ENV_PROD" > ./.env
            echo "PROFILE=prod" >> ./.env
            docker compose -f docker-compose.yml --env-file ./.env down
            docker compose -f docker-compose.yml --env-file ./.env pull
            docker compose -f docker-compose.yml --env-file ./.env up -d --build